---
- hosts: local
  become: yes
  vars:
    - ruby_version: 2.4.0
    - login_user: vagrant
  tasks:
    #- name: create directory
    #  file: dest=/home/{{ login_user }}/test_for_ansible state=directory owner=vagrant group=vagrant mode=755

    - name: install Development Tools
      yum: name="{{ item }}" state=present
      with_items:
        - "@Development Tools"

    - name: check rbenv installed
      command: test -x /home/{{ login_user }}/.rbenv
      register: rbenv_present
      ignore_errors: yes
      become: no
    - name: git clone rbenv
      git: repo=https://github.com/sstephenson/rbenv.git dest=/home/vagrant/.rbenv
      when: rbenv_present.rc != 0
      become: no
    - name: update bash_profile
      copy: src=bash_profile.custom dest=/home/{{ login_user }}/.bash_profile backup=yes
      become: no

    - name: check ruby-build installed
      command: test -x /home/{{ login_user }}/.rbenv/plugins/ruby-build
      register: rbuild_present
      ignore_errors: yes
      become: no
    - name: git clone ruby-build
      git: repo=https://github.com/sstephenson/ruby-build.git dest=/home/{{ login_user }}/.rbenv/plugins/ruby-build
      when: rbuild_present.rc != 0
      become: no

    - name: update rbenv
      command: git pull --rebase chdir=/home/{{ login_user }}/.rbenv
      become: no
    - name: update ruby-build
      command: git pull --rebase chdir=/home/{{ login_user }}/.rbenv/plugins/ruby-build

    - name: check ruby installed
      shell: /bin/bash -lc "rbenv versions | grep {{ ruby_version }}"
      register: ruby_installed
      ignore_errors: yes
      become: no
    - name: install ruby
      shell: /bin/bash -lc "rbenv install {{ ruby_version }} && rbenv rehash && rbenv global {{ ruby_version }}"
      when: ruby_installed.rc != 0
      become: no
