---
- name: check rbenv installed
  command: test -x /home/{{ WORK_USER }}/.rbenv
  register: rbenv_present
  ignore_errors: yes
- name: git clone rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=/home/{{ WORK_USER }}/.rbenv
  when: rbenv_present.rc != 0

- name: check ruby-build installed
  command: test -x /home/{{ WORK_USER }}/.rbenv/plugins/ruby-build
  register: rbuild_present
  ignore_errors: yes
- name: git clone ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=/home/{{ WORK_USER }}/.rbenv/plugins/ruby-build
  when: rbuild_present.rc != 0
- name: update bash_profile for rbenv
  blockinfile:
    dest: ~/.bash_profile
    content: |
      export PATH="$HOME/.rbenv/bin:$PATH"
      eval "$(rbenv init -)"

- name: update rbenv
  command: git pull --rebase chdir=/home/{{ WORK_USER }}/.rbenv
- name: update ruby-build
  command: git pull --rebase chdir=/home/{{ WORK_USER }}/.rbenv/plugins/ruby-build

- name: check ruby installed
  shell: /bin/bash -lc "rbenv versions | grep {{ RUBY_VERSION }}"
  register: ruby_installed
  ignore_errors: yes
- name: install ruby
  shell: /bin/bash -lc "rbenv install {{ RUBY_VERSION }} && rbenv rehash && rbenv global {{ RUBY_VERSION }}"
  when: ruby_installed.rc != 0

- name: check bundler installed
  shell: /bin/bash -lc "gem list | grep bundler"
  register: gem_bundler_installed
  ignore_errors: yes
- name: install bundler
  shell: /bin/bash -lc "gem install bundler"
  when: gem_bundler_installed.rc != 0
