export locale=ja_JP.UTF-8
export LANG=ja_JP.UTF-8
export LESSCHARSET=utf-8
## 新しく作られたファイルのパーミッションがつねに 644 になるようにする。基本。
umask 022
## core ファイルを作らせないようにする。これも基本。
ulimit -c 0
## 環境変数の設定
# rsync では ssh を使う。
export RSYNC_RSH=ssh

# 環境変数 LANG を消去する。日本語メッセージを出してほしくないため。
unset LANG

export PYTHONIOENCODING=utf-8
export PYTHONPATH=~/lib/python:.
# デフォルトのパス
PATH=~/bin:/usr/local/bin:/usr/X11R6/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

# "." コマンドでシェルスクリプトを実行するときは混乱するので PATH を検索させない。
shopt -u sourcepath

# bashオプション設定

# EOF (Ctrl-D) 入力は 10回まで許可。
IGNOREEOF=10
# 履歴のサイズ
HISTSIZE=50000
HISTFILESIZE=50000

# 履歴ファイルを上書きではなく追加する。
# 複数のホストで同時にログインすることがあるので、上書きすると危険だ。
shopt -s histappend
# "!"をつかって履歴上のコマンドを実行するとき、
# 実行するまえに必ず展開結果を確認できるようにする。
shopt -s histverify
# 履歴の置換に失敗したときやり直せるようにする。
shopt -s histreedit
# 端末の画面サイズを自動認識。
shopt -s checkwinsize
# "@" のあとにホスト名を補完させない。
shopt -u hostcomplete
# つねにパス名のテーブルをチェックする。
shopt -s checkhash
# なにも入力してないときはコマンド名を補完しない。
# (メチャクチャ候補が多いので。)
shopt -s no_empty_cmd_completion

# i: 直前の履歴 30件を表示する。引数がある場合は過去 1000件を検索する。
# (history で履歴全部を表示させると多すぎるので)
function i {
	if [ "$1" ]; then history 1000 | grep "$@"; else history 30; fi
}
# I: 直前の履歴 30件を表示する。引数がある場合は過去のすべてを検索する。
function I {
	if [ "$1" ]; then history | grep "$@"; else history 30; fi
}

# GNU screen 用のコマンド。引数を screen のステータス行に表示。
function dispstatus { 
	if [[ "$STY" ]]; then echo -en "\033k$1\033\134"; fi 
}

# 端末・プロンプトの設定
# いろんな関数

# つねに直前のコマンドの終了状態をチェックさせる。
# もし異常終了した場合は、その状態(数値)を表示する。
function showexit {
	local s=$?
		dispstatus "${PWD/\/home\/keisuke.takahashi/~}"
		if [[ $s -eq 0 ]]; then return; fi
			echo "exit $s"
}
PROMPT_COMMAND=showexit

# px: 長いプロンプトと短いプロンプトを切り換える。
function px {
	local tmp=$PS1; PS1=$PS0; PS0=$tmp; 
}

# h: csh における which と同じ。
function h { command -v $1; }

# wi: whatis の略。指定されたコマンドの実体を表示。
function wi {
	case `type -t "$1"` in
		alias|function) type "$1";;
		file) L `command -v "$1"`;;
		function) type "$1";;
		esac
}

# 現在実行中のジョブを表示。
function j { jobs -l; }

# 雑多な手抜き用コマンド。
function tmp { cd ~/tmp; }

alias vim='/usr/bin/vim -u /home/keisuke.takahashi/.vimrc'
alias view='/usr/bin/vim -R '

# エイリアス。

alias ls='ls -F'
alias ll='ls -o'   # 環境によっては -o はなく、-l を使う。
alias la='ls -lag'
# grep では LC_CTYPE はセットしない。遅いから。
alias g='env -u LC_CTYPE grep -i'
alias r='env -u LC_CTYPE grep -ir'
alias G='env -u LC_CTYPE grep'
alias F='env -u LC_CTYPE fgrep'
alias c=cat
# 確認つきファイル操作。rm, mv, cp などのあぶない操作はなるべくこれらを使う。
# コマンド名を rm や mv などに上書きしないのは、これらのエイリアスが指定されてない環境
# (root など) でうっかり生の rm などを (-i がついてると思って) 実行してしまうのを防ぐため。
alias rmi='rm -i'
alias mvi='mv -i'
alias cpi='cp -i'
alias lld='ls -ld'
alias ..='cd ..'
alias 644='chmod 644'
alias 755='chmod 755'
alias ox='od -Ax -tx1'
alias server='cd /var/www/'
alias assetController='cd /var/www/src/class/Toybox/Asset/Controller'
alias templates='cd /var/www/admin-tool/templates'
alias adminController='cd /var/www/src/class/Toybox/AdminTool/Controller'
alias adminProvider='cd /var/www/src/class/Toybox/AdminTool/Provider'
alias adminService='cd /var/www/src/class/Toybox/AdminTool/Service'
alias cascadeDataformat='cd /var/www/src/class/Toybox/Cascade/DataFormat'
alias jsx='cd /var/www/admin-tool'
alias phpLog='tail -f /var/log/php.log'
alias accessLog='tail -f /var/log/apache2/access.log'

alias graph='git log --graph --oneline --decorate=full'
alias gl='git log --graph --date=short'
alias gs='git -c color.ui=always status | less -REX'
alias gb='git branch'
alias gbr='git branch --remote'
alias gf='git fetch --prune'

export PYENV_ROOT=${HOME}/.pyenv
if [ -d "${PYENV_ROOT}" ]; then
	export PATH=${PYENV_ROOT}/bin:$PATH
	eval "$(pyenv init -)"
	eval "$(pyenv virtualenv-init -)"
fi

#export PATH="$HOME/.rbenv/bin:$PATH"
#eval "$(rbenv init -)"


source /home/keisuke.takahashi/git/git/contrib/completion/git-prompt.sh
source /home/keisuke.takahashi/git/git/contrib/completion/git-completion.bash
export PS1='\[\033[32m\]\u@\h\[\033[00m\]:\[\033[34m\]\w\[\033[31m\]$(__git_ps1)\[\033[00m\]\$ '
