---
- name: install python-devel
  yum: name=python-devel state=latest
  become: yes

- name: check pyenv installed
  command: test -x /home/{{ WORK_USER }}/.pyenv
  register: pyenv_present
  ignore_errors: yes
- name: git clone pyenv
  git: repo=https://github.com/yyuu/pyenv.git dest=/home/{{ WORK_USER }}/.pyenv
  when: pyenv_present.rc != 0
- name: update bash_profile for pyenv
  blockinfile:
    dest: ~/.bash_profile
    content: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"

- name: check pyenv-virtualenv installed
  command: test -x /home/{{ WORK_USER }}/.pyenv/plugins/pyenv-virtualenv
  register: pyvirtual_present
  ignore_errors: yes
- name: git clone pyenv-virtualenv
  git: repo=https://github.com/yyuu/pyenv-virtualenv.git dest=/home/{{ WORK_USER }}/.pyenv/plugins/pyenv-virtualenv
  when: pyvirtual_present != 0

- name: update pyenv
  command: git pull --rebase chdir=/home/{{ WORK_USER }}/.pyenv
- name: update pyenv-virtualenv
  command: git pull --rebase chdir=/home/{{ WORK_USER }}/.pyenv/plugins/pyenv-virtualenv

- name: check python installed
  shell: /bin/bash -lc "pyenv versions | grep {{ PYTHON_VERSION }}"
  register: python_installed
  ignore_errors: yes
- name: install python
  shell: /bin/bash -lc "pyenv install {{ PYTHON_VERSION }} && pyenv rehash && pyenv global {{ PYTHON_VERSION }}"
  when: python_installed.rc != 0

- name: install pip
  yum: name=python-pip state=latest
  become: yes

- name: upgrade pip
  command: pip install --upgrade pip 
  become: yes
