---
- name: install libselinux-python
  yum: name=libselinux-python state=latest
  become: yes
- name: remove localtime
  file: path=/etc/localtime state=absent
  become: yes
- name: change timezone
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes mode=0644
  become: yes
- name: change locale
  lineinfile: >-
    dest=/etc/sysconfig/i18n
    state=present
    regexp=^LANG=
    line='LANG="ja_JP.UTF-8"'
  become: yes

- name: install Development Tools
  yum: name="{{ item }}" state=present
  with_items:
    - "@Development Tools"
  become: yes

- name: install dependencies
  yum: name={{item}} state=present
  with_items:
    - gcc
    - openssl
    - openssl-devel
    - rpm-build
    - gcc-c++
    - bzip2
    - bzip2-devel
    - libtool
    - zlib
    - zlib-devel
    - httpd-devel
    - openssl-devel
    - curl-devel
    - ncurses-devel
    - gdbm-devel
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - bison
    - mysql-devel
  become: yes

#- name: check mysql55
#  command: yum search mysql55 -q
#  register: find_mysql55
#  ignore_errors: yes
#- name: rpm mysql-community-release-el6-5
#  when: find_mysql55.stderr == ""
#  command: rpm -Uvh --force http://dev.mysql.com/get/mysql-community-release-el6-5.noarch.rpm
#  become: yes
#- name: rpm mysql-community-release-el6-5
#  when: find_mysql55.stderr == ""
#  yum: name=mysql55-develop
#  become: yes
